---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: os-cluster
  namespace: default
spec:
  security:
    config:
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true
  general:
    httpPort: 9200
    serviceName: os-cluster
    setVMMaxMapCount: true
    version: 2.8.0
    pluginsList: []
    drainDataNodes: true
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.8.0
    enable: true
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: opensearch-nodepool-32
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: data
      replicas: 6
      nodeSelector:
        cloud.google.com/gke-nodepool: opensearch-nodepool-32
      diskSize: "500Gi"
      jvm: -Xmx31G -Xms31G
      resources:
        requests:
          memory: "64Gi"
          cpu: 16
        limits:
          memory: "64Gi"
          cpu: 16
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        pvc:
          storageClass: standard-rwo
          accessModes:
            - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: os-cluster-service
spec:
  type: LoadBalancer
  selector:
    opster.io/os-cluster: os-cluster
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards-service
spec:
  type: ClusterIP
  selector:
    opensearch.cluster.dashboards: os-cluster
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
