apiVersion: batch/v1
kind: Job
metadata:
  name: rally-big5-os
spec:
  completions: 100
  template:
    metadata:
      name: rally-big5-os
      labels:
        app: rally-opensearch
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: os-rally-node-big5
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rally-elasticsearch
              topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "kubernetes.io/arch"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: rally
          image: docker.elastic.co/employees/sachinfrayne/rally-custom-big5:2
          imagePullPolicy: Always
          env:
            - name: HOSTPORT
              value: "os-cluster.default.svc.cluster.local:9200"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: os-cluster-admin-password
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os-cluster-admin-password
                  key: password
            - name: META
              value: "product:Opensearch,product-version:Opensearch-3.1.0,benchmark-dataset:openai_vector,benchmark-id:big5-17-aug-2025-9.1.2-vs-3.1.0,benchmark-name:OS-BIG5"
          args:
            [
              "race",
              "--track-path=/rally/custom_tracks/big5",
              "--target-hosts=$(HOSTPORT)",
              "--pipeline=benchmark-only",
              "--user-tags=$(META)",
              "--on-error=abort",
              "--client-options=timeout:360,use_ssl:true,verify_certs:false,basic_auth_user:'$(USERNAME)',basic_auth_password:'$(PASSWORD)'",
              "--challenge=big5",
              "--exclude-tasks=delete-index,index-append,type:index,type:create-index,type:raw-request",
            ]
          volumeMounts:
            - name: rally-config-volume
              mountPath: "/rally/.rally/rally.ini"
              subPath: "rally.ini"
            - name: rally-base-dir
              mountPath: "/rally/.rally"
            - name: rally-tracks-data-os
              mountPath: "/rally-tracks-cache"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: rally-config-volume
          configMap:
            name: rally-config
            items:
              - key: rally.ini
                path: rally.ini
        - name: rally-base-dir
          emptyDir: {}
        - name: rally-tracks-data-os
          persistentVolumeClaim:
            claimName: rally-tracks-data-os
      initContainers:
        - name: permission-fix
          image: busybox
          command: ["sh", "-c"]
          args: ["chmod -R 777 /rally/.rally /rally-tracks-cache"]
          volumeMounts:
            - mountPath: /rally/.rally
              name: rally-base-dir
            - mountPath: /rally-tracks-cache
              name: rally-tracks-data-os
